version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    target-branch: updates
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    target-branch: updates
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
