changelog:
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement

    - title: "🐛 Fixes"
      labels:
        - bug

    - title: "📚 Documentation"
      labels:
        - documentation

    - title: "📦 Dependencies"
      labels:
        - dependencies

    - title: "🔧 CI and maintenance"
      labels:
        - github_actions

    - title: "Other changes"
      labels:
        - "*"
